import 'package:path/path.dart';
import 'package:sqflite/sqflite.dart';
import 'package:sana/app/data/models/message_model.dart';

class AppDatabase {
  // 1. Typo Fix: Renamed _privatevateConstructor to _privateConstructor
  AppDatabase._privateConstructor();

  static final AppDatabase instance = AppDatabase._privateConstructor();

  Database? _database;
  static const String _tableName = 'messages';

  Future<Database> get database async {
    if (_database != null) {
      return _database!;
    } else {
      _database = await _initDatabase();
      return _database!;
    }
  }

  Future<Database> _initDatabase() async {
    String dbPath = await getDatabasesPath();
    String path = join(dbPath, 'app_database.db');

    return await openDatabase(path, version: 1, onCreate: _onCreate);
  }

  Future _onCreate(Database db, int version) async {
    // 2. CRITICAL FIX: The schema must exactly match the keys generated by message.toJson()
    // I have mapped these based on your previous stack trace error log.
    await db.execute('''
      CREATE TABLE $_tableName (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        userMessage TEXT,
        message TEXT,
        status TEXT,
        bottimestamp TEXT,
        usertimestamp TEXT
      )
    ''');
  }

  // PUT (Update): Modify an existing record
  Future<int> updateMessage(MessageModel message) async {
    Database db = await database;

    return await db.update(
      _tableName,
      message.toJson(),
      where: 'id = ?',
      whereArgs: [message.id], // Strictly updates the row matching this ID
    );
  }

  // POST (Insert): Add a new record
  Future<int> insertMessage(MessageModel message) async {
    // 3. Optimization: Use 'await database' directly rather than 'await instance.database'
    // since we are already inside the class.
    Database db = await database;

    return await db.insert(
      _tableName,
      message.toJson(),
      conflictAlgorithm: ConflictAlgorithm.replace,
    );
  }

  // LOAD (Read): Fetch all records
  Future<List<MessageModel>> getMessage() async {
    Database db = await database;

    final List<Map<String, dynamic>> maps = await db.query(
      _tableName,
      orderBy: 'id DESC', // Newest first
    );

    return List.generate(maps.length, (i) {
      return MessageModel.fromJson(maps[i]);
    });
  }

  Future<int> deleteMessage(MessageModel message) async {
    Database db = await database;

    return await db.delete(
      _tableName,
      where: 'id = ?',
      whereArgs: [message.id],
    );
  }

  // Resource cleanup
  Future close() async {
    Database db = await database;
    db.close();
  }
}
